[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub && r.obj == p.obj && r.act == p.act


# 这里定义了一次权限请求包含三个部分:
# sub：谁发起请求，subject
# obj：访问什么，object
# act：执行什么操作，action